// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lambawebdev/go-bonus-system/internal/gophemart/repositories (interfaces: WithdrawalRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/lambawebdev/go-bonus-system/internal/gophemart/dto"
	entities "github.com/lambawebdev/go-bonus-system/internal/gophemart/entities"
)

// MockWithdrawalRepo is a mock of WithdrawalRepo interface.
type MockWithdrawalRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalRepoMockRecorder
}

// MockWithdrawalRepoMockRecorder is the mock recorder for MockWithdrawalRepo.
type MockWithdrawalRepoMockRecorder struct {
	mock *MockWithdrawalRepo
}

// NewMockWithdrawalRepo creates a new mock instance.
func NewMockWithdrawalRepo(ctrl *gomock.Controller) *MockWithdrawalRepo {
	mock := &MockWithdrawalRepo{ctrl: ctrl}
	mock.recorder = &MockWithdrawalRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalRepo) EXPECT() *MockWithdrawalRepoMockRecorder {
	return m.recorder
}

// CreateWithdrawal mocks base method.
func (m *MockWithdrawalRepo) CreateWithdrawal(arg0 context.Context, arg1 dto.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawal", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithdrawal indicates an expected call of CreateWithdrawal.
func (mr *MockWithdrawalRepoMockRecorder) CreateWithdrawal(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawal", reflect.TypeOf((*MockWithdrawalRepo)(nil).CreateWithdrawal), arg0, arg1)
}

// GetWithdrawals mocks base method.
func (m *MockWithdrawalRepo) GetWithdrawals(arg0 context.Context) ([]entities.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", arg0)
	ret0, _ := ret[0].([]entities.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockWithdrawalRepoMockRecorder) GetWithdrawals(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockWithdrawalRepo)(nil).GetWithdrawals), arg0)
}
