// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lambawebdev/go-bonus-system/internal/gophemart/repositories (interfaces: UserRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/lambawebdev/go-bonus-system/internal/gophemart/dto"
	entities "github.com/lambawebdev/go-bonus-system/internal/gophemart/entities"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// CheckIfUserLoginAlreadyExists mocks base method.
func (m *MockUserRepo) CheckIfUserLoginAlreadyExists(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfUserLoginAlreadyExists", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfUserLoginAlreadyExists indicates an expected call of CheckIfUserLoginAlreadyExists.
func (mr *MockUserRepoMockRecorder) CheckIfUserLoginAlreadyExists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfUserLoginAlreadyExists", reflect.TypeOf((*MockUserRepo)(nil).CheckIfUserLoginAlreadyExists), arg0)
}

// CreateUser mocks base method.
func (m *MockUserRepo) CreateUser(arg0 dto.User) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepoMockRecorder) CreateUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepo)(nil).CreateUser), arg0)
}

// GetExistingUser mocks base method.
func (m *MockUserRepo) GetExistingUser(arg0 string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExistingUser", arg0)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExistingUser indicates an expected call of GetExistingUser.
func (mr *MockUserRepoMockRecorder) GetExistingUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExistingUser", reflect.TypeOf((*MockUserRepo)(nil).GetExistingUser), arg0)
}
